apiVersion: v1
kind: Namespace
metadata:
  name: ns-bff
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff
  namespace: ns-bff
  labels:
    app: bff
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: bff
  template:
    metadata:
      labels:
        app: bff
    spec:
      containers:
      - name: bff
        image: tkdqja9573/ssafy-tailored-bff:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
        resources:
          requests:
            cpu: "300m"
          limits:
            cpu: "600m"
---
apiVersion: v1
kind: Service
metadata:
  name: bff
  namespace: ns-bff
  labels:
    app: bff
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: bff
  type: ClusterIP