spring:
  application:
    name: rank
  datasource:
    url: ENC(ND7ataPAw3IQRTlkDQ5m/rGseS+B8SXNqxugUiCkwUyfzkUxRxFpWA==)
    username: ENC(QwnUyIfu2THVsYXlzD2sow==)
    password: ENC(SOefXdn69nfyCpO4F6b8PSyBEKZhuFZs)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
